/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ProductCategory = IDL.Variant({
  'fertilizers' : IDL.Null,
  'other' : IDL.Null,
  'irrigation' : IDL.Null,
  'handTools' : IDL.Null,
  'machinery' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'productId' : IDL.Nat32,
  'quantity' : IDL.Nat,
});
export const InventoryItem = IDL.Record({
  'productId' : IDL.Nat32,
  'quantity' : IDL.Nat,
});
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
});
export const SalesOrder = IDL.Record({
  'id' : IDL.Nat32,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'totalAmount' : IDL.Float64,
  'timestamp' : IDL.Int64,
  'items' : IDL.Vec(OrderItem),
});
export const BusinessProfile = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'approvalStatus' : IDL.Text,
  'address' : IDL.Text,
  'affiliation' : IDL.Text,
  'contactNumber' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Product = IDL.Record({
  'id' : IDL.Nat32,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'category' : ProductCategory,
  'price' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addInventoryItem' : IDL.Func([IDL.Nat32, IDL.Nat], [], []),
  'addProduct' : IDL.Func(
      [IDL.Text, ProductCategory, IDL.Text, IDL.Float64],
      [IDL.Nat32],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrder' : IDL.Func(
      [IDL.Text, IDL.Vec(OrderItem), IDL.Float64],
      [IDL.Nat32],
      [],
    ),
  'getAllInventory' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(SalesOrder)], ['query']),
  'getBusinessProfile' : IDL.Func([], [BusinessProfile], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInventoryItem' : IDL.Func(
      [IDL.Nat32],
      [IDL.Opt(InventoryItem)],
      ['query'],
    ),
  'getOrder' : IDL.Func([IDL.Nat32], [IDL.Opt(SalesOrder)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat32], [IDL.Opt(Product)], ['query']),
  'getProductCatalog' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func(
      [ProductCategory],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getProductsByPriceRange' : IDL.Func(
      [IDL.Float64, IDL.Float64],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeInventoryItem' : IDL.Func([IDL.Nat32], [], []),
  'removeProduct' : IDL.Func([IDL.Nat32], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateInventoryItem' : IDL.Func([IDL.Nat32, IDL.Nat], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat32, OrderStatus], [], []),
  'updateProduct' : IDL.Func(
      [IDL.Nat32, IDL.Text, ProductCategory, IDL.Text, IDL.Float64, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ProductCategory = IDL.Variant({
    'fertilizers' : IDL.Null,
    'other' : IDL.Null,
    'irrigation' : IDL.Null,
    'handTools' : IDL.Null,
    'machinery' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'productId' : IDL.Nat32,
    'quantity' : IDL.Nat,
  });
  const InventoryItem = IDL.Record({
    'productId' : IDL.Nat32,
    'quantity' : IDL.Nat,
  });
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  });
  const SalesOrder = IDL.Record({
    'id' : IDL.Nat32,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'totalAmount' : IDL.Float64,
    'timestamp' : IDL.Int64,
    'items' : IDL.Vec(OrderItem),
  });
  const BusinessProfile = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'approvalStatus' : IDL.Text,
    'address' : IDL.Text,
    'affiliation' : IDL.Text,
    'contactNumber' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Product = IDL.Record({
    'id' : IDL.Nat32,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'category' : ProductCategory,
    'price' : IDL.Float64,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addInventoryItem' : IDL.Func([IDL.Nat32, IDL.Nat], [], []),
    'addProduct' : IDL.Func(
        [IDL.Text, ProductCategory, IDL.Text, IDL.Float64],
        [IDL.Nat32],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrder' : IDL.Func(
        [IDL.Text, IDL.Vec(OrderItem), IDL.Float64],
        [IDL.Nat32],
        [],
      ),
    'getAllInventory' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(SalesOrder)], ['query']),
    'getBusinessProfile' : IDL.Func([], [BusinessProfile], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInventoryItem' : IDL.Func(
        [IDL.Nat32],
        [IDL.Opt(InventoryItem)],
        ['query'],
      ),
    'getOrder' : IDL.Func([IDL.Nat32], [IDL.Opt(SalesOrder)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat32], [IDL.Opt(Product)], ['query']),
    'getProductCatalog' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [ProductCategory],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsByPriceRange' : IDL.Func(
        [IDL.Float64, IDL.Float64],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeInventoryItem' : IDL.Func([IDL.Nat32], [], []),
    'removeProduct' : IDL.Func([IDL.Nat32], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateInventoryItem' : IDL.Func([IDL.Nat32, IDL.Nat], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat32, OrderStatus], [], []),
    'updateProduct' : IDL.Func(
        [IDL.Nat32, IDL.Text, ProductCategory, IDL.Text, IDL.Float64, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };