/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BusinessProfile {
  'name' : string,
  'description' : string,
  'approvalStatus' : string,
  'address' : string,
  'affiliation' : string,
  'contactNumber' : string,
}
export interface InventoryItem { 'productId' : number, 'quantity' : bigint }
export interface OrderItem { 'productId' : number, 'quantity' : bigint }
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null };
export interface Product {
  'id' : number,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'category' : ProductCategory,
  'price' : number,
}
export type ProductCategory = { 'fertilizers' : null } |
  { 'other' : null } |
  { 'irrigation' : null } |
  { 'handTools' : null } |
  { 'machinery' : null };
export interface SalesOrder {
  'id' : number,
  'customerName' : string,
  'status' : OrderStatus,
  'totalAmount' : number,
  'timestamp' : bigint,
  'items' : Array<OrderItem>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addInventoryItem' : ActorMethod<[number, bigint], undefined>,
  'addProduct' : ActorMethod<[string, ProductCategory, string, number], number>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrder' : ActorMethod<[string, Array<OrderItem>, number], number>,
  'getAllInventory' : ActorMethod<[], Array<InventoryItem>>,
  'getAllOrders' : ActorMethod<[], Array<SalesOrder>>,
  'getBusinessProfile' : ActorMethod<[], BusinessProfile>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInventoryItem' : ActorMethod<[number], [] | [InventoryItem]>,
  'getOrder' : ActorMethod<[number], [] | [SalesOrder]>,
  'getProduct' : ActorMethod<[number], [] | [Product]>,
  'getProductCatalog' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[ProductCategory], Array<Product>>,
  'getProductsByPriceRange' : ActorMethod<[number, number], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeInventoryItem' : ActorMethod<[number], undefined>,
  'removeProduct' : ActorMethod<[number], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateInventoryItem' : ActorMethod<[number, bigint], undefined>,
  'updateOrderStatus' : ActorMethod<[number, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<
    [number, string, ProductCategory, string, number, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];